-- DCGM - CYGI License.
-- Copyright (c) 2025 Victor Fuchadzhy.
-- BVG: Controllers group.

function boot()
    bvg_con_audio.boot()
    bvg_con_editor.boot()
    
    bvg_con_render.set_glitch_power(0)
end

function notify_config_changed()
    bvg_con_render.notify_config_changed()
    bvg_con_brightness.notify_config_changed()
    bvg_con_blocker.notify_config_changed()
end

function update()
    bvg_con_latch_animator.update()
    bvg_con_blocker.update()
    bvg_con_render.update()
end