local vision_effect_id = {
    ["nightvision_1"] = 0,
    ["nightvision_2"] = 1,
    ["nightvision_3"] = 2
}

function try_get_vision_effect_id(section)
    local effect_str = ini_sys:r_string_ex(section, "nv_effect")

    if (effect_str == nil) then
        return -1
    end

    local effect_id = vision_effect_id[effect_str]

    if (effect_id == nil) then
        return -1;
    end

    return effect_id
end