-- THIS SCRIPT IS OBSOLETE. 
-- Look bvg_monkey.script for actual logic.

-- Referenced by:
-- liz_fdda_redone_headgear_animations (G.A.M.M.A. 0.9.4)
-- uni_anim_detectors (G.A.M.M.A. 0.9.4)
-- uni_anim_knives (G.A.M.M.A. 0.9.4)

-- Referenced by: fix_beefnvg_anim (G.A.M.M.A. 0.9.4)
-- mc_anm_time_1 = 0

-- Referenced by: fix_beefnvg_anim (G.A.M.M.A. 0.9.4)
-- torch_anm_time = 0

-- Referenced by: item_device (G.A.M.M.A. 0.9.4)
-- play_animation = true